### ISSUE TITLE
File menu is partially empty

### ISSUE THREAD

**Issue by FrancoisBeaune** [lucasg/Dependencies#101]
With a [build of master downloaded from AppVeyor](https://ci.appveyor.com/project/lucasg/dependencies/builds/28547419/job/6p4vxru8vg53k84q/artifacts):

![image](https://user-images.githubusercontent.com/16878244/69807263-25f1ad80-11e5-11ea-8a23-8b9b6631b75b.png)

**Comment by lucasg** [comment]
Fixed in b2f3603f03ad9400fbfb0f185bdaf2df693730b0 :

![image](https://user-images.githubusercontent.com/2520861/71562972-91e76000-2a88-11ea-824e-e35b52e064a8.png)

**Comment by FrancoisBeaune** [comment]
This fix didn't make it into v1.10 right? Because I've downloaded v1.10 and the bug's still there.

**Comment by lucasg** [comment]
no it's the trunk unfortunately (I don't do backward fixes on releases because it's a hassle).
you can still get the nightlies though
