### ISSUE TITLE
Dependency api-ms-win-core-wow64-l1-1-0.dll not found

### ISSUE THREAD

**Issue by FrancoisBeaune** [lucasg/Dependencies#102]
With a [build of master downloaded from AppVeyor](https://ci.appveyor.com/project/lucasg/dependencies/builds/28547419/job/6p4vxru8vg53k84q/artifacts):

![image](https://user-images.githubusercontent.com/16878244/69807400-79fc9200-11e5-11ea-833d-8a2ebb950e4b.png)

The DLL exists on my system, albeit on a different path:

![image](https://user-images.githubusercontent.com/16878244/69807324-4f123e00-11e5-11ea-8c27-973f8fed7410.png)

**Comment by lucasg** [comment]
Ok I've "fixed" this issue : for some reason, when an apiset entry is present in the apiset map but points to an empty target (such as `api-ms-win-core-wow64`), the loader falls back to `kernelbase.dll`.

I don't really understand where this  `kernelbase.dll` appears in the loading sequence, but hardcoding it seem to do the trick :
![image](https://user-images.githubusercontent.com/2520861/71585635-91e27100-2b17-11ea-9dfe-f3cc10fba42f.png)

**Comment by lucasg** [comment]
Fuck, `api-ms-win-core-winrt-string-l1-1-0.dll` falls back to `combase.dll`. not `kernelbase.dll` ...

**Comment by lucasg** [comment]
Ok, there was two bugs :

1. apiset lookup disregard the "build' number part, e.g. `api-ms-win-core-winrt-string-l1-1-0.dll` will be search as `api-ms-win-core-winrt-string-l1-1`m and will match with `api-ms-win-core-winrt-string-l1-1-1` which points to `combase.dll`
2. `String.Compare` is "localized" (WTF ?) and don't do a proper ASCII string comparison

By the way, this is fixed now

**Comment by FrancoisBeaune** [comment]
Thanks for the fixes!

**Comment by dandan19830409** [comment]
Hello!
I'm having the same problem too with a C++ and fortran mixed .EXE software. In Dependencies it says api-ms-win-core-wow64-l1-1-0.dll cannot be found. Could you tell me how did you fix this Problem by hardcoding it? i.e. how to link it to kernelbase.dll? Thanks.

Kind Regards,
Dan

> 
> 
> Ok, there was two bugs :
> 
>     1. apiset lookup disregard the "build' number part, e.g. `api-ms-win-core-winrt-string-l1-1-0.dll` will be search as `api-ms-win-core-winrt-string-l1-1`m and will match with `api-ms-win-core-winrt-string-l1-1-1` which points to `combase.dll`
> 
>     2. `String.Compare` is "localized" (WTF ?) and don't do a proper ASCII string comparison
> 
> 
> By the way, this is fixed now

**Comment by lucasg** [comment]
@dandan19830409 : apiset redirection is done by the compiler. My guess is you're using a fairly recent visual studio (vs 2015/2017/2019) but you're trying to run the exe on Windows 7 which have an older apiset. Am I right ?

**Comment by dandan19830409** [comment]
> Windows
Hi, 
Thanks for the fast reply.
Yes. I'm using VS2015 to produce an EXE file on windows 10. It can not be executed due to missing DLLs. But before this, the file produced by VS2015 on windows 7 was okay. The source codes are of course the same.

Kind regards,
Dan

**Comment by lucasg** [comment]
The easiest solution to ensure your binary can run on all supported platform is to compile it with `"/MT"`
One little example :

**"/MT"**
```
PS O:\Dependencies\Dependencies> .\bin\Debugx64\Dependencies.exe -imports "C:\Users\lucas\source\repos\TestWow64Apisets\x64\Release\TestWow64Apisets.exe"                                                                                                                                                   [-] Import listing for file : C:\Users\lucas\source\repos\TestWow64Apisets\x64\Release\TestWow64Apisets.exe
Import from module KERNEL32.dll :
         Function GetCurrentProcess
         Function IsWow64Process
         Function RtlCaptureContext
         Function RtlLookupFunctionEntry
         Function RtlVirtualUnwind
         Function UnhandledExceptionFilter
         Function SetUnhandledExceptionFilter
         Function TerminateProcess
         Function IsProcessorFeaturePresent
         Function QueryPerformanceCounter
         Function GetCurrentProcessId
         Function GetCurrentThreadId
         Function GetSystemTimeAsFileTime
         Function InitializeSListHead
         Function IsDebuggerPresent
         Function GetStartupInfoW
         Function GetModuleHandleW
         Function RtlUnwindEx
         Function GetLastError
         Function SetLastError
         Function EnterCriticalSection
         Function LeaveCriticalSection
         Function DeleteCriticalSection
         Function InitializeCriticalSectionAndSpinCount
         Function TlsAlloc
         Function TlsGetValue
         Function TlsSetValue
         Function TlsFree
         Function FreeLibrary
         Function GetProcAddress
         Function LoadLibraryExW
         Function GetStdHandle
         Function WriteFile
         Function GetModuleFileNameA
         Function MultiByteToWideChar
         Function WideCharToMultiByte
         Function ExitProcess
         Function GetModuleHandleExW
         Function GetCommandLineA
         Function GetCommandLineW
         Function GetACP
         Function HeapFree
         Function HeapAlloc
         Function CompareStringW
         Function LCMapStringW
         Function GetFileType
         Function CloseHandle
         Function FindClose
         Function FindFirstFileExA
         Function FindNextFileA
         Function IsValidCodePage
         Function GetOEMCP
         Function GetCPInfo
         Function GetEnvironmentStringsW
         Function FreeEnvironmentStringsW
         Function SetEnvironmentVariableA
         Function SetStdHandle
         Function GetStringTypeW
         Function GetProcessHeap
         Function FlushFileBuffers
         Function GetConsoleCP
         Function GetConsoleMode
         Function HeapSize
         Function HeapReAlloc
         Function SetFilePointerEx
         Function WriteConsoleW
         Function CreateFileW
         Function RaiseException
[-] Import listing done
```

**"/MD"**
```
[-] Import listing for file : C:\Users\lucas\source\repos\TestWow64Apisets\x64\Release\TestWow64Apisets.exe
Import from module KERNEL32.dll :
         Function GetCurrentProcess
         Function IsWow64Process
         Function IsDebuggerPresent
         Function InitializeSListHead
         Function GetSystemTimeAsFileTime
         Function GetCurrentThreadId
         Function GetCurrentProcessId
         Function QueryPerformanceCounter
         Function IsProcessorFeaturePresent
         Function TerminateProcess
         Function SetUnhandledExceptionFilter
         Function UnhandledExceptionFilter
         Function RtlVirtualUnwind
         Function RtlLookupFunctionEntry
         Function RtlCaptureContext
         Function GetModuleHandleW
Import from module VCRUNTIME140.dll :
         Function __C_specific_handler
         Function memset
Import from module api-ms-win-crt-stdio-l1-1-0.dll :
         Function __stdio_common_vfprintf
         Function _set_fmode
         Function __p__commode
         Function __acrt_iob_func
Import from module api-ms-win-crt-runtime-l1-1-0.dll :
         Function _initialize_onexit_table
         Function _register_onexit_function
         Function exit
         Function _crt_atexit
         Function __p___argv
         Function terminate
         Function __p___argc
         Function _register_thread_local_exe_atexit_callback
         Function _c_exit
         Function _initterm_e
         Function _initterm
         Function _get_initial_narrow_environment
         Function _initialize_narrow_environment
         Function _configure_narrow_argv
         Function _cexit
         Function _set_app_type
         Function _seh_filter_exe
         Function _exit
Import from module api-ms-win-crt-math-l1-1-0.dll :
         Function __setusermatherr
Import from module api-ms-win-crt-locale-l1-1-0.dll :
         Function _configthreadlocale
Import from module api-ms-win-crt-heap-l1-1-0.dll :
         Function _set_new_mode
[-] Import listing done
```

You can notice there is no dependency to apisets dll when compiling with `"/MT"

**Comment by mardukbp** [comment]
@lucasg It would be great if you published a release that includes this fix. Thanks!

**Comment by josdemmers** [comment]
Switched to a new laptop and noticed this problem after I downloaded the latest version of dependencies (1.10).
My old laptop still had 1.5 installed, with that version it works fine.

**Comment by asfarley** [comment]
Bump! I also would be happy if there was a fix available.
