### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by glassgiant** [lucasg/Dependencies#103]
I can't seem to find much in terms of documentation, and with no context-sensitive tips, it's a bit difficult to figure out what's what.  For example, I have a question mark icon next to a red exclamation point, next to MSVCR80.dll, which I assume means it's missing/not findable, but it would be nice to be able to confirm that.
![image](https://user-images.githubusercontent.com/1236012/70325893-7da59f80-1809-11ea-88fd-f917605735d2.png)

**Comment by lucasg** [comment]
Great idea ! I've added tooltip for module's status describing what's wrong with them :

![image](https://user-images.githubusercontent.com/2520861/70395048-2a933e80-19fb-11ea-9208-4b08204786cd.png)
![image](https://user-images.githubusercontent.com/2520861/70395057-40086880-19fb-11ea-9fee-fc002111d9f4.png)

If you have any other suggestion on where I should put tooltip, feel free to add it to the issue tracker.

**Comment by glassgiant** [comment]
That's great. Thanks!
