### ISSUE TITLE
Crash in undecorator

### ISSUE THREAD

**Issue by MarekKnapek** [lucasg/Dependencies#108]
Steps to reproduce:
 - Download and unzip v1.10.
 - Run release version for x86 on Windows 7 x64.
 - Main menu -> File -> Open.
 - Open itself (DependenciesGui.exe).
 - Click on first DLL (C:\Windows\SysWOW64\mscoree.dll).
 - CRASH!

I tried to attach an debugger after program startup and before crash and I observed a few things:
 - The crash happens in file ref.c, in function PhDereferenceObject, on line 243, variable objectHeader has address of 0xFFFFFFF8.
 - That is probably because function sooner on call stack named UndecorateSymbolDemangleName failed to undecorate name in file demangle.cpp on line 221 and is passing a NULL variable into PhDereferenceObject on line 228.
 - I think, the program failed to demangle "_CorExeMain" function name.
 - Probably because UnDecorateSymbolNameW function was not found.
 - Because dbghelp.dll was not loaded.
 - Because you tried to load x64 version of that DLL into x86 process in file UnmanagedSymPrv.cpp, on line 70.
 - This failed and you tried to load dbghelp.dll from current directory.
 - But this failed because some dependency was not satisfied.
 - dbghelp.dll depends on _o_memset function from api-ms-win-crt-private-l1-1-0.dll library.
 - But that export is not found in that DLL.

So, I think you brought in modern dbghelp.dll (version 10) but not all its dependencies.

I think you should load x86 DLL into x86 process from Windows SDK first. If it fails you should use system version of dbghelp.dll (version 6.1 on Windows 7) and not distribute your own, I don't think it is worth the hassle. If you want to distribute your own version, test if it works correctly first please.

Also, I think you should not dereference NULL object in demangle.cpp file on line 228.

Best Regards,
Marek

**Comment by MarekKnapek** [comment]
![dependencies-dbghelp](https://user-images.githubusercontent.com/13893067/71768562-5250c600-2f17-11ea-9b23-fa53012d1c5b.png)

**Comment by MarekKnapek** [comment]
I think this issue will not manifest itself on Windows 10, because Windows 7 doesn't have api-ms-win-crt-private-l1-1-0.dll in its API-Set, but Win10 does. So Win10 will load this dependency from Api-Set and not form this file from Dependencies installation.

**Comment by lucasg** [comment]
Your analysis is spot on. I've fixed it with 446e201cfd6f7fd0d2a67c499dd2ff74aaa2a913

**Comment by MarekKnapek** [comment]
Hi Lucas, I saw your commit and I think it would not work on 32bit Windows because there is no Program Files (x86) folder there. I did not test this because I'm on mobile only right now.

**Comment by lucasg** [comment]
Yep, fixed it 826fda88b1513a4a3ccdca421fe62075323eb28b
