### ISSUE TITLE
Ordinals and hints shall be 16bit numbers

### ISSUE THREAD

**Issue by MarekKnapek** [lucasg/Dependencies#109]
Ordinals and hints shall be unsigned 16bit numbers, but Dependencies displays them as signed 32bit numbers. Tested on 64bit Windows 7 with 64bit Dependencies v1.10.0.0 inspecting a 64bit version of API Monitor (https://www.rohitab.com/apimonitor).

Best regards,
Marek Knápek

![16vs32a](https://user-images.githubusercontent.com/13893067/72577427-06b4f980-38d3-11ea-94ff-221add768a8c.png)

![16vs32b](https://user-images.githubusercontent.com/13893067/72577444-17656f80-38d3-11ea-9704-69cc2ecbe3d3.png)

**Comment by lucasg** [comment]
Commit 9335b2cca5966dce80f40c7dcdc16dfb0df510e4 correctly display hints and ordinals as 16-bit unsigned integers, but this does not fix #110 (reason is elsewhere)

Thanks anyway,

Lucas

**Comment by MarekKnapek** [comment]
Hi Lucas, I tested build v1.9.312 downloaded from https://ci.appveyor.com/project/lucasg/dependencies/builds/30521285 and sadly, I must say, that this issue is not fixed. Please see attached screenshots.

![issue109a](https://user-images.githubusercontent.com/13893067/73657154-fc944880-4691-11ea-9698-1c1ef2a1c62f.png)

![issue109b](https://user-images.githubusercontent.com/13893067/73657167-0027cf80-4692-11ea-9a67-44815a48fbaa.png)

![issue109c](https://user-images.githubusercontent.com/13893067/73657172-01f19300-4692-11ea-9364-c742bd6c6900.png)

![issue109d](https://user-images.githubusercontent.com/13893067/73657177-04ec8380-4692-11ea-880f-a3470582024b.png)

**Comment by MarekKnapek** [comment]
I would like to re-open this issue, but I'm not sure I'm allowed to do it.

**Comment by lucasg** [comment]
Is it how they are displayed that bothers you ? Because internally there are stored as `ushort` or `UInt16` 
Anyway, I've changed it:

![image](https://user-images.githubusercontent.com/2520861/73690120-f58c2b00-46cf-11ea-9c33-9dbf45185cf2.png)

**Comment by MarekKnapek** [comment]
Yes, that was my problem. Ordinals and hints are internally 16bit numbers but your program displayed them as 32bit numbers with long 0x0000 prefix. So people could be mistaken and think that they are 32bit numbers. I would like people not to be mistaken.

I opened a lot of issues for you recently, I hope that it does't annoy you too much. The tool is great and I would like it to be also correct.

**Comment by MarekKnapek** [comment]
I downloaded and tested 32bit build 1.9.313 from https://ci.appveyor.com/project/lucasg/dependencies/builds/30546249 and I confirm that this bug is now fixed. Thank you.
