### ISSUE TITLE
Feature request: copy table to clipboard

### ISSUE THREAD

**Issue by OfekShilon** [lucasg/Dependencies#11]
I see in the import/export grids it is possible to select all or multiple lines - which is very nice -but copying the selection and pasting it gives only a concatenation of the 'Function' column contents.

Ideally all the selected line contents would be copyable, with tabs between consecutive fields in a line and newlines between lines.

**Comment by lucasg** [comment]
Done. `Ctrl+C` now copy all selected lines in a CSV format :

```
Hint, Ordinal, Name, VA, demangler
```
```
2 (0x00000002), 1 (0x00000001), Ordinal_2, 0x0003d680, None
3 (0x00000003), 2 (0x00000002), Ordinal_3, 0x0003d860, None
N/A, 3 (0x00000003), CiCheckSignedFile, 0x000287a0, None
N/A, 4 (0x00000004), CiFindPageHashesInCatalog, 0x00028860, None
N/A, 5 (0x00000005), CiFindPageHashesInSignedFile, 0x000288e0, None
```

**Comment by OfekShilon** [comment]
Thank you!
