### ISSUE TITLE
Could not display all exports

### ISSUE THREAD

**Issue by MarekKnapek** [lucasg/Dependencies#110]
Dependencies fails to display any exports from apimonitor-drv-x64.sys file, a static dependency to apimonitor-x64.exe. Tested on 64bit Windows 7 with 64bit Dependencies v1.10.0.0 inspecting a 64bit version of API Monitor (https://www.rohitab.com/apimonitor).

Best regards,
Marek Knápek

![16vs32a](https://user-images.githubusercontent.com/13893067/72577427-06b4f980-38d3-11ea-94ff-221add768a8c.png)

![16vs32b](https://user-images.githubusercontent.com/13893067/72577444-17656f80-38d3-11ea-9704-69cc2ecbe3d3.png)

**Comment by lucasg** [comment]
Commit 9335b2cca5966dce80f40c7dcdc16dfb0df510e4 correctly display hints and ordinals as 16-bit unsigned integers, but this does not fix #109 (reason is elsewhere)

Thanks anyway,

Lucas

**Comment by MarekKnapek** [comment]
I tested build v1.9.312 downloaded from https://ci.appveyor.com/project/lucasg/dependencies/builds/30521285 and Dependencies shows some exports now. But they are not valid, created issue#124.
