### ISSUE TITLE
Could not find GDIPlus.dll

### ISSUE THREAD

**Issue by MarekKnapek** [lucasg/Dependencies#111]
GDIPlus.dll could not be found, probably because it is redirected by SxS. You can find it by inspecting so called system compatible manifest, in my case located at `c:\Windows\winsxs\Manifests\amd64_microsoft.windows.systemcompatible_6595b64144ccf1df_6.0.7600.16385_none_020095e6d39a70fd.manifest` or `c:\Windows\winsxs\Manifests\x86_microsoft.windows.systemcompatible_6595b64144ccf1df_6.0.7600.16385_none_49adccbde8169a03.manifest`. Or read so called system default activation context (probably created from the manifest) located at process environment block `PEB->SystemDefaultActivationContextData`. You might find that code at https://github.com/deroko/activationcontext to be very helpful.

Best regards,
Marek Knápek

**Comment by MarekKnapek** [comment]
Could be related to issue #112 - Wrong version of common controls is found.

**Comment by lucasg** [comment]
Found the culprit, some sxs publisher manifests are present but not the dll associated.
There is a check now.

(Doesn't fix #112 though)

**Comment by MarekKnapek** [comment]
Hi Lucas, I don't understand why is this issue marked as closed, it is definitely not fixed yet. I tested build 1.9.321 downloaded from https://ci.appveyor.com/project/lucasg/dependencies/builds/31478826. I analyzed calc.exe with it and it still cannot find gdiplus.dll.

I would like to re-open this issue.

**Comment by Neustradamus** [comment]
I confirm the problem...
