### ISSUE TITLE
Reporting missing imports even when nothing is really missing

### ISSUE THREAD

**Issue by MarekKnapek** [lucasg/Dependencies#114]
Tested on Windows 7 x64, running Dependencies 32bit v1.10.0.0, examining Dependency Walker 32bit. Possibly because examined EXE is importing by ordinal from DLL that exports by name? Also, I needed to disable dbghelp.dll in Dependencies directory because of issue #108 - Crash in undecorator.

Best regards,
Marek Knápek

![MissingImports1](https://user-images.githubusercontent.com/13893067/72655071-ddf43900-3992-11ea-9f3f-4e12b92bcf67.png)

![MissingImports2](https://user-images.githubusercontent.com/13893067/72655082-e51b4700-3992-11ea-8e46-f66b898af3b8.png)

**Comment by lucasg** [comment]
I can reproduce the bug with v1.10, but not with the current master build so I may have already fixed it.
Anyway I keep the ticket opened since I need to do something smarter than shipping windows 10's `dbghelp.dll` on older systems

**Comment by MarekKnapek** [comment]
I guess you can distribute the same version of dbghelp as Dr. Memory ( https://drmemory.org/ ) is distributing. It is version 6.3 (suggesting it is taken from Windows 8.1) which does not depend on ApiSchema DLLs.

**Comment by MarekKnapek** [comment]
I tested it in build 1.9.314 downloaded from https://ci.appveyor.com/project/lucasg/dependencies/builds/30546840 and it works fine now.
