### ISSUE TITLE
APISet doesn't work on Win7

### ISSUE THREAD

**Issue by MarekKnapek** [lucasg/Dependencies#119]
Tested on Windows 7 64bit. Open Dependencies v1.10.0.0 64bit Release and inspect notepad.exe 64bit. Expand advapi32.dll, observe that API-MS-Win-Service-Core-L1-1-0.dll is listed as found on disk. Do the same on Windows 10 64bit, inspect notepad.exe 64bit, expand advapi32.dll, observe that API-MS-Win-Service-Core-L1-1-0.dll is redirected to sechost.dll by APISetSchema.

**Comment by MarekKnapek** [comment]
Eh, my mistake, these DLLs are redirected on Winwos 8 and newer, not on Windows 7. My bad. Please close or delete this issue.

**Comment by lucasg** [comment]
Ok I found the root cause of the bug : apiset lookups was done case sensitive-wise, where Windows usually accepts both cases.

89dbce69cd51c6884356f1c91b71d607b7830f40 fix this

**Comment by MarekKnapek** [comment]
I tested build version 1.9.321 downloaded from https://ci.appveyor.com/project/lucasg/dependencies/builds/31478826 and I confirm that mentioned DLLs are resolved as redirected by APISet instead of found as files on disk. Good job. Thank you.
