### ISSUE TITLE
-apisetsdll command line throws and crashes

### ISSUE THREAD

**Issue by MarekKnapek** [lucasg/Dependencies#121]
Execute `Dependencies.exe -apisetsdll` on command line. The program prints an exception and then crashes. It should write an error message about missing file name.

```
Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Dependencies.Program.Main(String[] args) in C:\projects\dependencies\Dependencies\Program.cs:line 698
```

**Comment by OfekShilon** [comment]
What is this option?  Do you mean `-apisets` ?  For me this one works perfectly.

**Comment by MarekKnapek** [comment]
No, if you run the command line version of this tool without any parameters, there will be help with list of commands. One of them is apisets as you say, another one is apisetsdll as I say. The problem is, that this command expects path to apiset dll, but doesn't get one. So it throws an out of bounds exception and crashes. I'm on mobile now, so I cannot provide more print-outs right now.

**Comment by lucasg** [comment]
I've fixed it, now the cli does some basic param validation https://github.com/lucasg/Dependencies/commit/76730c5965af37c73f8a51733af1cc4e9adaba5d

```
PS O:\Dependencies\Dependencies> .\bin\Debugx64\Dependencies.exe -apisetsdll
[x] Command DumpApiSets needs to have a PE <FILE> argument

Dependencies.exe : command line tool for dumping dependencies and various utilities.

Usage : Dependencies.exe [OPTIONS] <FILE>

Options :
  -h -help : display this help
  -json : activate json output.
  -apisets : dump the system's ApiSet schema (api set dll -> host dll)
  -apisetsdll : dump the ApiSet schema from apisetschema <FILE> (api set dll -> host dll)
  -knowndll : dump all the system's known dlls (x86 and x64)
  -manifest : dump <FILE> embedded manifest, if it exists.
  -sxsentries : dump all of <FILE>'s sxs dependencies.
  -imports : dump <FILE> imports
  -exports : dump <FILE> exports
  -modules : dump <FILE> resolved modules
  -chain : dump <FILE> whole dependency chain
```

**Comment by MarekKnapek** [comment]
I downloaded and tested 32bit build 1.9.310 from https://ci.appveyor.com/project/lucasg/dependencies/builds/30362745 and I confirm that this bug is now fixed. Thank you.
