### ISSUE TITLE
Not all dependencies shown

### ISSUE THREAD

**Issue by MarekKnapek** [lucasg/Dependencies#122]
Steps to reproduce:
 - Start Windows 7 32bit.
 - Unzip Dependencies v1.10.0.0 32bit release.
 - Rename or delete dbghelp.dll, because it causes troubles.
 - Start Dependencies.
 - Inspect Dependency Walker.
 - Only two DLLs are shown, rest is missing.

![dependencies32](https://user-images.githubusercontent.com/13893067/73116933-f6d68e80-3f3e-11ea-8daa-b78076af96c0.png)

**Comment by lucasg** [comment]
I don't reproduce this issue with the current master build. I keep the ticket open since I will test it again with the future next release

**Comment by MarekKnapek** [comment]
Hi Lucas, I tested build 1.9.310 and it is still broken. Then I tested build 1.9.311 and it is already fixed. Good work. Thank you.
