### ISSUE TITLE
Displays nonexistent exports

### ISSUE THREAD

**Issue by MarekKnapek** [lucasg/Dependencies#124]
Dependencies displays bogus exports, it displays much more lines than Dependency Walker does. Please see attached screenshots. Tested on Windows 7 64bit, inspecting APIMonitor application (http://www.rohitab.com/apimonitor) running Dependencies build v1.9.312 downloaded from https://ci.appveyor.com/project/lucasg/dependencies/builds/30521285.

![issue109a](https://user-images.githubusercontent.com/13893067/73657154-fc944880-4691-11ea-9698-1c1ef2a1c62f.png)

![issue109b](https://user-images.githubusercontent.com/13893067/73657167-0027cf80-4692-11ea-9a67-44815a48fbaa.png)

![issue109c](https://user-images.githubusercontent.com/13893067/73657172-01f19300-4692-11ea-9364-c742bd6c6900.png)

![issue109d](https://user-images.githubusercontent.com/13893067/73657177-04ec8380-4692-11ea-880f-a3470582024b.png)

**Comment by lucasg** [comment]
Well, PE parsers don't agree on this case :) 
But `dumpbin` (which is my reference) gives the following result:

```console
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>dumpbin /EXPORTS "O:\Dependencies\Dependencies\tests\issue110\api-monitor-v2r13-x86-x64\API Monitor (rohitab.com)\apimonitor-drv-x64.sys"
Microsoft (R) COFF/PE Dumper Version 14.22.27905.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file O:\Dependencies\Dependencies\tests\issue110\api-monitor-v2r13-x86-x64\API Monitor (rohitab.com)\apimonitor-drv-x64.sys

File Type: DLL

  Section contains the following exports for apimonitor-drv-x64.sys

    00000000 characteristics
    5141EFAB time date stamp Thu Mar 14 16:41:31 2013
        0.00 version
       57005 ordinal base
          65 number of functions
           0 number of names

    ordinal hint RVA      name

      57005      00001B90 [NONAME]
      57007      00001500 [NONAME]
      57034      00001BE0 [NONAME]
      57069      00005A10 [NONAME]

  Summary

        7000 .data
        2000 .pdata
        8000 .rdata
        1000 .reloc
        1000 .rsrc
       1A000 .text
```

Anyway I've fixed it:
```console
PS O:\Dependencies\Dependencies> .\bin\Debugx64\Dependencies.exe -exports 'O:\Dependencies\Dependencies\tests\issue110\api-monitor-v2r13-x86-x64\API Monitor (rohitab.com)\apimonitor-drv-x64.sys'                                                                                              [-] Export listing for file : O:\Dependencies\Dependencies\tests\issue110\api-monitor-v2r13-x86-x64\API Monitor (rohitab.com)\apimonitor-drv-x64.sys
Export 57005 :
         Name :
         VA : 0x1B90
Export 57007 :
         Name :
         VA : 0x1500
Export 57034 :
         Name :
         VA : 0x1BE0
Export 57069 :
         Name :
         VA : 0x5A10
[-] Export listing done
```

**Comment by MarekKnapek** [comment]
I'm not sure what you meant by dumpbin's output, it lists 4 exported functions.

I downloaded and tested build 1.9.314 from https://ci.appveyor.com/project/lucasg/dependencies/builds/30546840 and I confirm that this bug is now fixed. Thank you.
