### ISSUE TITLE
Problem with building solution

### ISSUE THREAD

**Issue by MrMajorThorburn** [lucasg/Dependencies#127]
I was not able to complete a build using VS 2015 due to some problem with an item with 141 in its name that was not available as part of the associated SDK. It was in the next version of the SDK but VS 2015 would not allow me to use that so decided to try upgrading to VS 2017.
Got a minor moan in the upgrade report, namely
DependenciesAppx\DependenciesAppx.wapproj: The application which this project type is based on was not found.
I decided to go ahead with the build and sorted out a problem with the pfx file being missing but just copied the enc file and remove the enc bit.
The only error I have now is 
Error	MSB4044	The "GenerateDesktopBridgeAppxManifest" task was not given a value for the required parameter "EntryPointExe".	DependenciesAppx	D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.targets
for which I have no solution.
Can anyone help me?

**Comment by lucasg** [comment]
`DependenciesAppx` is not a proper target, it was a test thingy. You can unload it from the solution, it's fine.

**Comment by lucasg** [comment]
Ok, I've completely removed the appx target you should be okay : 85ad794b2d5eda7839d2c74e1308070def8a5025
