### ISSUE TITLE
Feature request: Search / find in tree

### ISSUE THREAD

**Issue by hoegge** [lucasg/Dependencies#13]
It would be very useful to be able to search the tree for DLLs and Entrypoints (names). E.g. I am trying to figure out why a specific DLL is loaded and by what.

**Comment by lucasg** [comment]
You can search a particular dll via the context menu :

![image](https://user-images.githubusercontent.com/2520861/36935491-aa61562e-1ef8-11e8-8e14-47930c5c9734.png)

Having a global search utility could be probably useful, however it's not in my current roadmap.

(You can also filter dll results, as well as Imports and Exports, by pressing Ctrl+F in any list views).
