### ISSUE TITLE
Security warnings about v1.10/Dependencies_x64_Release.zip 

### ISSUE THREAD

**Issue by amai2012** [lucasg/Dependencies#132]
Trying to download the offered binary distribution from https://github.com/lucasg/Dependencies/releases/download/v1.10/Dependencies_x64_Release.zip I realized that a couple of security software suites complains about  it or block the download at all.
Here's a public report from https://www.virustotal.com/gui/file/44df956dbe267e0a705224c3b85d515fee2adc87509861e24fb6c6b0ea1b86d6/detection

While some scanners seem to complain about the low-level nature of this tool an `adware` warning is present as well.

**Comment by lucasg** [comment]
There is a packaging without peview : https://github.com/lucasg/Dependencies/releases/download/v1.10/Dependencies_x64_Release_.without.peview.exe.zip

Peview is a third party binary that is wrongly detected as "hack tool" by some av

**Comment by amai2012** [comment]
That is _fine_ according to https://www.virustotal.com/gui/file/4d8589d65878ed23e72ac7100c45bcb75cfc02120c1a276f1573210e229ac2cb/detection

Maybe that should be the default download?!

**Comment by lucasg** [comment]
Fun fact : Dependencies repackage most of the code in peview, but is considered fine by most AVs !

And no, I don't want to make it this the default download just because the AV industry is a shit show
