### ISSUE TITLE
Windows 10 api-ms-win-core-wow64-11-1-0.dll not found

### ISSUE THREAD

**Issue by rjsargent** [lucasg/Dependencies#135]
On my Windows 10 system, C:\Windows\SysWOW64\WS2_32.dll shows a dependency on api-ms-win-core-wow64-11-1-0.dll but cannot find it. Does it need to be added to Dependencies?

The error message when clicking on it is also a little odd. "We could not find api-ms-win-core-wow64-11-1-0.dll file on the disk **_anymore_**, ...". Was it ever there?

p.s. Thanks for bringing us this updated implementation!

**Comment by lucasg** [comment]
Hi, 

Can you test it please with the current master build : https://ci.appveyor.com/api/buildjobs/u9dgn4w6dgf9j549/artifacts/output%2FDependencies_x64_Release.zip ?

I've tested on my side and I can't reproduce your issue, I've recently fixed a bug in the api-set resolver so I may also fixed your issue.

Cheers

**Comment by rjsargent** [comment]
That does the trick. This time there are no complaints about missing
modules.
 
Thanks! You can close this issue.

  _____

**Comment by mardukbp** [comment]
@lucasg It would be great if you published a release that includes this fix. Thanks!
