### ISSUE TITLE
Search folders customization dialog too restrictive

### ISSUE THREAD

**Issue by bouffa** [lucasg/Dependencies#145]
Adding entries to the search folders is too restrictive, it would be simpler to let the user copy/paste paths instead of going through the full folders tree to pick one. This would also make using network paths much easier.
Thank you!

**Comment by lucasg** [comment]
I've improved it a bit using TextBox for editing paths manually with commit https://github.com/lucasg/Dependencies/commit/2229847774ff8c32005938acdb3c4618fc9f7011

![image](https://user-images.githubusercontent.com/2520861/87851477-667b7400-c8f9-11ea-952b-e0f2002eedab.png)


It's still a bit clunky, but it's kinda like environment variables editing modal :

![image](https://user-images.githubusercontent.com/2520861/87851458-4350c480-c8f9-11ea-86d4-3d9e21d173aa.png)

**Comment by MHendricks** [comment]
Thanks for this. It fixes my biggest complaint about DependenciesGui. Not being able to paste and reorder search paths. This is wonderful and almost deserves its own release version 😃.
