### ISSUE TITLE
Json output is not currently supported when dumping the dependency chain

### ISSUE THREAD

**Issue by mgnslndh** [lucasg/Dependencies#156]
When using the CLI tool `dependencies.exe` and you combine the `-json` option with the `-chain` option you are presented with the following message:

```
Json output is not currently supported when dumping the dependency chain
```

It would be really nice to get this output formatted as json. 

Would you consider a PR for this functionality? I'd like to help out as part of [Hacktoberfest 2020](https://twitter.com/hacktoberfest).

**Comment by lucasg** [comment]
I've finally found the time to implement it : https://github.com/lucasg/Dependencies/commit/a8de425beb76a087cdbd7982ed8fb3979727a30c
