### ISSUE TITLE
Font selection

### ISSUE THREAD

**Issue by dan2001o** [lucasg/Dependencies#16]
Hi,
thank you for your wonderful program
unfortunately I can't read the results very well
pls, I propose you would like to add a font selection font
Kind regards,
dan

**Comment by lucasg** [comment]
I've added a rudimentary font selector :

![image](https://user-images.githubusercontent.com/2520861/44029869-3b9b1a2c-9eff-11e8-888f-be516e412490.png)

![image](https://user-images.githubusercontent.com/2520861/44029877-450281fe-9eff-11e8-86d9-c8fc9b294dcc.png)

![image](https://user-images.githubusercontent.com/2520861/44029894-5115fe44-9eff-11e8-9b02-0037fe74fc9f.png)

![image](https://user-images.githubusercontent.com/2520861/44029907-5b56bbf0-9eff-11e8-8e5b-06bf07f60b6e.png)


Cheers,

Lucas
