### ISSUE TITLE
 False detections by Kaspersky products for Dependencies_x64_Release.zip 

### ISSUE THREAD

**Issue by chucklu** [lucasg/Dependencies#164]
According https://support.kaspersky.com/us/1870,
The scan result of the zip file on https://opentip.kaspersky.com is 
11/23/2020 4:59:50 PM	Deleted	legitimate software that can be used by intruders to damage your computer or personal data not-a-virus:UDS:RiskTool.Win32.ProcHack	C:\Users\clu\Downloads\Dependencies_x64_Release.zip	Low	

I have already submit a re-analyze request to the kaspersky. I will record the reply of them later.

**Comment by pzhlkj6612** [comment]
Hi! Please see #26 .

In order to use this tool normally, you can try `Dependencies_*without.peview.exe.zip` from Release or CI.

**Comment by chucklu** [comment]
@pzhlkj6612  Thanks
