### ISSUE TITLE
stupid .net dependency

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [lucasg/Dependencies#171]
can you provide a version without requiring to installing that stupid .net crap? otherwise your project is just junk.

**Comment by jzakrzewski** [comment]
The project is apparently written (mostly) in C#, so .NET is required.

> otherwise your project is just junk.

Can we agree that that's unnecessary?

**Comment by MyTDT-Mysoft** [comment]
> The project is apparently written (mostly) in C#, so .NET is required.
> 
> > otherwise your project is just junk.
> 
> Can we agree that that's unnecessary?

sure, unecessary to have a project that suppose to be nice... ruined by terrible choice of language.
