### ISSUE TITLE
Sometimes Dependecies does not show delayload info correctly

### ISSUE THREAD

**Issue by vyv03354** [lucasg/Dependencies#177]
Steps to reproduce:
1. Install Firefox 87.
2. Open firefox.exe and mozglue.dll using Dependecies.
3. Expand mozglue.dll branch in the firefox.exe tab.

Actual result:
In the firefox.exe tab, version.dll under mozglue.dll has an hourglass icon even though it is not delayloaded.
version.dll under firefox.exe has an hourglass icon (correct).
In the mozglue.dll tab, version.dll has no hourglass icon (correct).

Expected result:
In the firefox.exe tab, version.dll under mozglue.dll should have no hourglass icon.

**Comment by lucasg** [comment]
You're right, I might actually be a little too aggressive when de-duplicating already seen modules in the tree list

**Comment by lucasg** [comment]
Fixed with : https://github.com/lucasg/Dependencies/commit/f88e561c8e2f7acd6da49b0c36c3b153ca32d1a8

![image](https://user-images.githubusercontent.com/2520861/118364063-38a5a100-b597-11eb-860c-0397a68584d3.png)

**Comment by vyv03354** [comment]
Verified with the latest CI build. Thank you.
