### ISSUE TITLE
Enhancement - Show ordinals used for DLL's not found, just like Dependency Walker

### ISSUE THREAD

**Issue by gg185069** [lucasg/Dependencies#179]
![image](https://user-images.githubusercontent.com/67160573/114055165-80c9f900-985e-11eb-9f65-85359fc0841f.png)

**Comment by lucasg** [comment]
I have already implemented it: 
![image](https://user-images.githubusercontent.com/2520861/118371795-7c57d500-b5ae-11eb-85db-3d2c89b4abfb.png)

However you may have to wait for 1.11 to be released to enjoy it
