### ISSUE TITLE
can you please support 32-bit OS?

### ISSUE THREAD

**Issue by toddfraser88** [lucasg/Dependencies#18]
can you please support 32-bit OS? I'm using windows 10 32-bit and i'd like to use your program.

**Comment by sonya75** [comment]
It does support 32 bit OS, its a python script.

**Comment by lucasg** [comment]
There is a 32-bit version of Dependencies since v1.8 : https://github.com/lucasg/Dependencies/releases/tag/v1.8. Can you tell if it works on 32-bit OS ?
