### ISSUE TITLE
Cannot run DependenciesGui

### ISSUE THREAD

**Issue by fmaeseele** [lucasg/Dependencies#183]
Hi,
When launching DependenciesGui, nothing happens.
Looking at the event viewer, here is the error:

Application : DependenciesGui.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.UnauthorizedAccessException
   à MS.Internal.Text.TextInterface.Native.Util.ConvertHresultToException(Int32)
   à MS.Internal.Text.TextInterface.FontList.get_Item(UInt32)
   à MS.Internal.FontFace.TypefaceCollection+Enumerator.get_Current()
   à Dependencies.FontFamilyListItem.IsSymbolFont(System.Windows.Media.FontFamily)
   à Dependencies.FontFamilyListItem..ctor(System.Windows.Media.FontFamily)
   à Dependencies.UserSettings.InitializeFontFamilyList()
   à Dependencies.UserSettings.OnInitialized(System.EventArgs)
   à System.Windows.FrameworkElement.TryFireInitialized()
   à MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(System.Xaml.XamlType, System.Object, Boolean)

Informations sur l'exception : System.Windows.Markup.XamlParseException
   à System.Windows.Markup.XamlReader.RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
   à System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   à System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   à System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   à Dependencies.UserSettings..ctor()
   à Dependencies.MainWindow..ctor()
   à Dependencies.App.App_Startup(System.Object, System.Windows.StartupEventArgs)
   à System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
   à System.Windows.Application.<.ctor>b__1_0(System.Object)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   à System.Windows.Threading.DispatcherOperation.InvokeImpl()
   à MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   à System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   à MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   à System.Windows.Threading.DispatcherOperation.Invoke()
   à System.Windows.Threading.Dispatcher.ProcessQueue()
   à System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   à MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   à MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   à System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   à MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   à MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   à System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   à System.Windows.Application.RunDispatcher(System.Object)
   à System.Windows.Application.RunInternal(System.Windows.Window)
   à Dependencies.App.Main()

My configuration:
Lenovo Yogo 9i
Windows 10 Pro (10943.1023)
Native Microsoft Windows Defender active
AdGuard 7
Visual Studio 2019 Preview.

Regards,
François

**Comment by matukeso** [comment]
Hi.
I encountered same problem. 
After uninstalling "Cascadia Code" font, DpendenciesGui launches normally.

**Comment by fmaeseele** [comment]
Hi,

 

Thank you for your help.

Indeed, I found out that  « Cascadia Code » and « Cascadia Mono » where installed into the fonts folder with no access right for my user… Very strange issue.

I think it is related to « Windows Terminal Preview » application.

It now works but Github web site seems to have issue so I can’t set the issue as resolved.

 

Best Regards,

François

 

De : matukeso ***@***.***> 
Envoyé : mardi 8 juin 2021 12:18
À : lucasg/Dependencies ***@***.***>
Cc : Kytie ***@***.***>; Author ***@***.***>
Objet : Re: [lucasg/Dependencies] Cannot run DependenciesGui (#183)

 

Hi.
I encountered same problem.
After uninstalling "Cascadia Code" font, DpendenciesGui launches normally.
