### ISSUE TITLE
I always forget which are imports vs exports

### ISSUE THREAD

**Issue by DaveInCaz** [lucasg/Dependencies#185]
As an occasional user of Dependencies and DW before it, for some reason I continually forget which list is the imports vs. the exports. Probably because I'm often studying some obscure third party library this isn't obvious as it would be if you were loading a DLL you created yourself.

My suggestion is to add something to the GUI to label the main panels. Perhaps this could be optional, or only occur on mouseover, or something like that. But I think a clear visual clue would be helpful and also an improvement over the original DW, IIRC.

Thanks

**Comment by lucasg** [comment]
I've added tooltips: https://github.com/lucasg/Dependencies/commit/bc94c3f698e9d0aeeab483a2624c32b1cf3380c4

![image](https://user-images.githubusercontent.com/2520861/129482218-27d1c5a8-8cf9-41d7-96ab-c07023ec73b9.png)

![image](https://user-images.githubusercontent.com/2520861/129482225-807b5d73-0af7-4410-a6bb-240e73dc6a57.png)

**Comment by DaveInCaz** [comment]
That's awesome, thank you!
