### ISSUE TITLE
peview.exe in 1.10 release identified as Hacktool.ProcHack by Symantec

### ISSUE THREAD

**Issue by Troy-K** [lucasg/Dependencies#186]
I downloaded the compiled project from the link in README.md
(https://github.com/lucasg/Dependencies/releases/download/v1.10/Dependencies_x64_Release.zip)
Before I unzipped it Symantec identified peview.exe as malware (Hacktool.ProcHack)

I guess it is a false positive, but I thought you should know.

**Comment by pzhlkj6612** [comment]
Hi. Please see #26 .

**Comment by pzhlkj6612** [comment]
And the version number in the title is wrong. 1.1 and 1.10 are not the same thing.

**Comment by Troy-K** [comment]
> 
> 
> Hi. Please see #26 .

Thanks.  I did try to search before reporting but I didn't see that closed issue.  Maybe because it is still an issue?
