### ISSUE TITLE
Removal of BinaryCache.Instance lazy initialization causes  null object exception to be thrown by Dependencies.exe

### ISSUE THREAD

**Issue by JustinLye** [lucasg/Dependencies#188]
@lucasg may I have access to push a branch and create a pull request? I found a null object exception is thrown from Dependencies.exe with command: `Dependecies.exe -depth=1 -modules <path-to-dll>`.

![image](https://user-images.githubusercontent.com/22377921/128122715-3c6797aa-e57e-414a-a848-0425dac8dea9.png)

I would like to create a PR for the following change, which resolves the issue of a null object exception:

![image](https://user-images.githubusercontent.com/22377921/128122862-92395cf1-3794-4c62-8b63-00d3cca20b24.png)

Debugging:
![image](https://user-images.githubusercontent.com/22377921/128123334-1f2101c6-3d23-4d48-8e5c-a5e123cf533f.png)

**Comment by jzakrzewski** [comment]
You don't need a push access to create a PR. The way it goes, you fork the repository, push a branch to your fork and then use github's UI to create a PR from your repository.

**Comment by lucasg** [comment]
I added a flag to init BinaryCache when needed : https://github.com/lucasg/Dependencies/commit/2524f6985708c45c34271c796ec25444d64fa662

Thanks for the bug report, feel free to do a PR next time !
