### ISSUE TITLE
What is the difference between these two "error" icons?

### ISSUE THREAD

**Issue by DaveInCaz** [lucasg/Dependencies#189]
![image](https://user-images.githubusercontent.com/18285074/129024999-2c7150b6-d6d4-4898-82d6-26655ea2b2c7.png)

When I hover over either of these the tooltip says the same thing: "... module has missing imports."

Thanks

**Comment by lucasg** [comment]
The second dll is delay-loaded : it will be loaded only if one of its exports is called by the parent module at runtime.
The first one is automatically loaded if the parent module is loaded
