### ISSUE TITLE
Dependencies won't run on Windows 10 64-bit (IoT) LTSB 2016 Enterprise

### ISSUE THREAD

**Issue by gmatian** [lucasg/Dependencies#19]
I extracted the zip and ran DependenciesGui.exe on a Windows 7 64 bit OS. It worked after I installed .NET 4.6.1. However, the same thing on a Window 10 IOT LTSB 2016 Enterprise edition fails to load.

The DependenciesGui.exe simply doesn't load (no prompts, dialogs or anything). Dependencies.exe however gets "Dependencies has stopped working" error and pops command line window with this error:

"**System.IO.FileNotFoundException: Could not load file or assembly 'ClrPhlib.dll' or one of its dependencies. The specified module could not be found. at Dependecnies.Program.Main(String[] args)"**

.NET 4.6.1 is already installed on this laptop.

**Comment by lucasg** [comment]
OK, stupid question : Is `ClrPhlib.dll` present in the same folder as Dependencies tools (GUI and CLI) ? an AV may have removed it.

Is  Window 10 IOT LTSB 2016 Enterprise a 32-bit OS ? If that's the case, `Dependencies` won't run since it has been built for as a 64 bit application.

**Comment by gmatian** [comment]
Yes, the dll in question is present in the same folder as the tool. The Windows 10 image is 64-bit but an LTSB (Long-Term Servicing Branch) version meant for enterprises, which our corporation has deployed. I wanted to use this tool to see which intrinsic or app specific call causes our app to crash with the message "<app name> has  stopped working." This occurs when my app tries to perform a "Save as..." operation or when the app is loaded directly invoked. There is another method of loading the app and that's why I'm able to get to the Save as... step in the first place. Hope this helps.

Thanks!

**Comment by gmatian** [comment]
One other thing I missed in my reply. you mentioned (GUI and CLI). The directory where I extracted the Dependencies.zip package has the following exe's but nothing with CLI:
- Dependencies.exe
- DependenciesGui.exe
- preview.exe
 No sign of any exe with CLI in it.

**Comment by gmatian** [comment]
I think I have resolved the issue. I installed the VC++ redistributable for VS 2017 x64 and that seem to do the trick. Thank you for this great tool.

**Comment by lucasg** [comment]
Yeah I've added a `NB` part in the `README` regarding this issue, but I should make it more obvious.
