### ISSUE TITLE
Win7 x64 SP2 crashing 

### ISSUE THREAD

**Issue by fafayqa** [lucasg/Dependencies#190]
This app is crashing immediatelly after opening up, loading anything, and clicking inside!

**Comment by lucasg** [comment]
Hmm, win7 SP2 is locked behind a ESU key no ? If that's the case, I can't really reproduce the bug since I don't know how to buy one

**Comment by TautvydasZilys** [comment]
I also ran into this on a fresh install of Windows 7 SP1. It seems to be an issue in the distributed API sets:

![image](https://user-images.githubusercontent.com/1092489/137556354-f962d5e3-4cb3-48d7-abfb-bd5fc7e4ab09.png)

Replacing all these API set files with the ones from Windows SDK 10.0.19041 (`C:\Program Files (x86)\Windows Kits\10\Redist\10.0.19041.0\ucrt\DLLs\x64` on my machine) including ucrtbase.dll makes it work again. I suspect the API set redist DLLs are getting taken from an older Windows SDK than the app is built with.
