### ISSUE TITLE
[Suggestion] Make the opened module selected when opening

### ISSUE THREAD

**Issue by OfekShilon** [lucasg/Dependencies#2]
The blank screen is confusing.
Besides, great tool! Thanks for sharing it

**Comment by lucasg** [comment]
is that better to you ?
 
![image](https://user-images.githubusercontent.com/2520861/33663886-ea27ce60-da91-11e7-8a33-1ba4b7deea22.png)

**Comment by OfekShilon** [comment]
Great!  thanks a lot
