### ISSUE TITLE
UI Bug - Sorting Glyph does not Reset when Import Export List change

### ISSUE THREAD

**Issue by yangshengf** [lucasg/Dependencies#201]
1. Open Dependencies UI
2. Open a file with dependency
3. Select 1 file
4. Click on a column header in Import or Export List which causes the list to be sorted
5. Select another file

Expected: Glyph resets because the list is no longer sorted by that column

Actual: Glyph is not reset

**Comment by lucasg** [comment]
thanks for the bugreport and the fix 👍
