### ISSUE TITLE
Enhancement: GUI option for depth limit

### ISSUE THREAD

**Issue by aslze** [lucasg/Dependencies#203]
The CLI has a `-depth` option to limit recursion. But the GUI only has *Child only* or *recursive* (with no limit) [direct or all].

In some files the GUI hangs forever with recursive (direct imports only). It would be good to have a setting for recursion limit.

**Comment by lucasg** [comment]
done : https://github.com/lucasg/Dependencies/commit/1997a40000b77bd3326cbc33672a7b9f78bb23f3
