### ISSUE TITLE
peview.exe not found

### ISSUE THREAD

**Issue by sdynan-r7** [lucasg/Dependencies#23]
I tried x64 Dependencies, but **right-click->View Module in Peviewer** tells me **peview.exe not found**.

![peviewnotfound](https://user-images.githubusercontent.com/36160644/42318004-b04863d0-8045-11e8-8732-3c003e5e5142.png)

![dependenciesfolder](https://user-images.githubusercontent.com/36160644/42318011-b640c71e-8045-11e8-83db-ac276f786163.png)

**Comment by lucasg** [comment]
Did you download the `v1.8` : https://github.com/lucasg/Dependencies/releases/tag/v1.8 ?
I've checked any of the zipped binary packages (`Debug`/`Release`, and `x86`/`x64`) and `peview.exe` is present in it.

Alternatively, you can set `peview.exe` (or any PE analyzer) path in the settings window.

**Comment by dripfeed** [comment]
Yes, I downloaded 1.8. And ran it on Windows 10 x64. You can see in one of the screenshots that `peview.exe` is present in my unzipped folder, but `DependenciesGui.exe` just doesn't find it (same problem with the x86 version).

Great tool, by the way.

**Comment by lucasg** [comment]
There was actually a typo in the default settings. This commit fix it : https://github.com/lucasg/Dependencies/commit/c1a748afc4efbe556ab350f240492a94303a6fb7.
