### ISSUE TITLE
Could not load file or assembly or one of its dependencies, ClrPhlib

### ISSUE THREAD

**Issue by tomcourt** [lucasg/Dependencies#24]
When trying to load v1.8 on Windows 8.1.

**Comment by wpa1160** [comment]
You need to download the lastest Microsoft Visual C++ Redistributable for Visual Studio 2017:
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

Direct link here: https://aka.ms/vs/15/release/vc_redist.x64.exe

**Comment by lucasg** [comment]
@wpa1160 : Thanks, that was my guess too.

@tomcourt : you are the first person I know to test Dependencies on Win8.1 !  Congratulation, you've been hired as a beta-tester 😄
