### ISSUE TITLE
[ DependenciesGui ] Opening a DLL with the same path but different contents shows the same result.

### ISSUE THREAD

**Issue by manx98** [lucasg/Dependencies#249]
When I use DependenciesGui to open DLLs with the same path but different contents it always shows the first result.

**Comment by pzhlkj6612** [comment]
Hi.
Did you re-open DependenciesGui? If not, I think it might be the same as #54 .

**Comment by manx98** [comment]
> Hi. Did you re-open DependenciesGui? If not, I think it might be the same as #54 .

Yes, it's the same problem. I will close this issue.
