### ISSUE TITLE
Publish Windows Binaries

### ISSUE THREAD

**Issue by GregB-Roberts** [lucasg/Dependencies#25]
Hi
Would it be possible to publish the windows binaries as i am finding i cant build them ?
Maybe relates to expected SDK, not sure.

THanks

**Comment by ComFreek** [comment]
See the *.zip files at https://github.com/lucasg/Dependencies/releases.

Honestly, though, I didn't find them either on my first contact with this project.

Even though the "Installation and Usage" paragraph in the readme states "Just click on one of the release numbers above", I'd suggest adding a big "Download" button *at the top* of the readme.
At least I didn't skim the rest of the readme after I saw the big screenshot and determined that this program is exactly what I needed.

**Comment by lucasg** [comment]
@GregB-Roberts , @ComFreek : do you talk about `https://github.com/lucasg/Dependencies` or `https://lucasg.github.io/Dependencies/` when you say the download link should be bigger ?

Anyway I've bumped up the download link at the top of the page.

**Comment by ComFreek** [comment]
@lucasg I didn't even know https://lucasg.github.io/Dependencies/ existed. I am not sure if linking to it from the repo readme is useful since it essentially provides the same information just in a more beautiful way.
Anyway, the download links in both cases look fine now! Thanks!

**Comment by GregB-Roberts** [comment]
Thanks! Great tool and fast
