### ISSUE TITLE
Not parsing API set for ntoskrnl.exe

### ISSUE THREAD

**Issue by ionescu007** [lucasg/Dependencies#39]
When loading ntoskrnl.exe on Windows 10 in system32, the ext-ms-win API contracts don’t seem to be resolved correctly. However this works for kernel32.dll.
I’d like to use this in my training class but this is a blocker ;-)

**Comment by lucasg** [comment]
Well the API contracts are correctly resolved : 
```
PS> .\Dependencies.exe -apisets | select-string werkernel
ext-ms-win-ntos-werkernel-l1-1 -> [ werkernel.sys ] 
```
It's just that all Host dlls are located in `C:\Windows\System32\drivers` while ntoskrnl.exe is in `C:\Windows\System32`. It seems that Winload is able to add `C:\Windows\System32\drivers` to the dll search resolution paths one way or another.

In the meantime, I wrote a quick and dirty way to simulate this mecanism by allowing the user to add custom search folders :

![image](https://user-images.githubusercontent.com/2520861/49115443-1e7a8a00-f29b-11e8-9b35-892339890259.png)

You need to drag and drop the folders you want to add to the custom path (yeah I know it's not ideal) :

![image](https://user-images.githubusercontent.com/2520861/49115556-6699ac80-f29b-11e8-8741-8fd5d158520a.png)

Once you validate your custom paths, the analysis starts over :

![image](https://user-images.githubusercontent.com/2520861/49115641-a19be000-f29b-11e8-8a0b-7860330c1f68.png)

There are still some dependencies not found, but those are not even properly resolved by the apiset :

```
PS> .\Dependencies.exe -apisets | select-string "ntos-(ksr|ksecurity|stateseparation)"
ext-ms-win-ntos-ksecurity-l1-1 -> [  ]
ext-ms-win-ntos-ksr-l1-1 -> [  ]
ext-ms-win-ntos-stateseparation-l1-1 -> [  ] 
```

Either there is still a bug in the apiset resolver, or the host dll are simply not present and ntoskrnl.exe does not care :p

Cheers,

**Comment by lucasg** [comment]
you can find the latest build here : https://ci.appveyor.com/api/buildjobs/ch987ymixuc51gh0/artifacts/output%2FDependencies_x64_Release.zip

**Comment by ionescu007** [comment]
Ah yes, I should've noticed that CNG.SYS was also not being found. The same bug is present in Dependency Walker, so I'm glad you fixed it. The Windows loader does indeed 'hardcore' that \drivers is a legitimate search path.

Ksecurity/KSR/StateSeparation are not present in Desktop/Server builds of Windows.

Note that "Api-" DLLs are required for load, while "ext-" DLLs are not. A sugar/bonus feature might be that when an "api-" set is not resolved, you could show a warning/error icon (the app will refuse to load), but when an "ext-" set is not resolved, you could show a more 'friendly' "this is not a problem" icon. But now I'm just being difficult :)

**Comment by ionescu007** [comment]
Nit: clicking "customize search directories" before having opened a file for analysis will crash the program. And the dialog is auto-sized too small :)

**Comment by lucasg** [comment]
Thanks for the explanation, I'll find a way to display this information for "optional" DLLS either via a tooltip or a custom icon. And the search paths dialog is definitively a work in progess :smile: 

As a final note, `Dependencies` is pretty much done as a project (there probably won't be a V2 or a major overhaul) so I'm opened to fixes and suggestions from people that use this tool. Feel free to file issues if something gripes you !
