### ISSUE TITLE
Crash on wrong format of PATH

### ISSUE THREAD

**Issue by suzuryo3893** [lucasg/Dependencies#49]
I found that DependenciesGUI.exe crashes with a particular DLL.
First, I opened the target DLL, then one line, which shows a name of the target DLL, was shown. There were no dependencies shown.
After that I clicked the line and then it crashed.

Here it is a screenshot of a dependency tree on DependencyWalker with the target DLL.
I built this DLL on my environment with some special building option. The original source is [here](https://github.com/opencv/opencv/releases/tag/3.3.1).
<img width="313" alt="dw_ss" src="https://user-images.githubusercontent.com/26302348/51305082-38f00900-1a7d-11e9-99ad-af899f1dcc5c.png">

I confirmed that DependenciesGUI.exe could open tbb,dll, cudart64_80.dll, zlib1.dll without crash.

**Comment by suzuryo3893** [comment]
I realized the reason why it happened.
My environment has a typo in PATH environment variable. A semicolon was used instead of a colon.

As a result, a variable "CandidateFolders" included invalid path "C", so Path.Combine function aborted in [DependenciesLib/FindPeModule.cs#L42](https://github.com/lucasg/Dependencies/blob/master/DependenciesLib/FindPeModule.cs#L42).

**Comment by lucasg** [comment]
hmm, I don't manage to reproduce your bug. Even if `CandidateFolders` has an invalid entry, `Path.Combine` should not throw an exception (and `Dependencies` need to recover from it).

Can you give me your PATH env ? Thanks

**Comment by suzuryo3893** [comment]
I guess you may need to doublequote paths for each to recall the situation.
Double quotations will be added automatically in case of including semicolon in a corresponding path if you use the list editor, which is a new feature of Win10.
Here are screenshots.

<img width="597" alt="ss_depends_exec" src="https://user-images.githubusercontent.com/26302348/51447806-fd975800-1d64-11e9-82e2-aca4164438f4.png">

<img width="441" alt="ss_depends_vars" src="https://user-images.githubusercontent.com/26302348/51447808-fff9b200-1d64-11e9-99a4-a277137ffcf6.png">

**Comment by suzuryo3893** [comment]
I pulled and tried then it worked well. Thank you.
