### ISSUE TITLE
Drag and drop support

### ISSUE THREAD

**Issue by sherief** [lucasg/Dependencies#5]
Just imagine being able to drag a DLL file from Explorer and drop it on Dependencies.exe. Mmmmmmmm

**Comment by eodabash** [comment]
Yes! This was the first thing I tried after downloading today only to find it didn't work 😁

**Comment by lucasg** [comment]
like this : http://recordit.co/2eF32ylJ8e ?

Well if you didn't found the feature, there is probably a UX issue underneath 😄

**Comment by eodabash** [comment]
Hmm I get the forbidden cursor whenever I try to drag something over the window. Maybe it's something particular to my system though.

**Comment by lucasg** [comment]
Interesting. What's your system (Windows version, x86/x64, .Net version, etc.) ?

**Comment by eodabash** [comment]
Windows 10 64-bit. looks like I have .NET 4.6 installed. I thought I would try to see what's happening in the debugger but I'm getting tons of build errors about missing ntstatus.h. Is there any trick to setting up the right build environment?

**Comment by baldurk** [comment]
Another data point - the drag and drop works for me if I build locally (debug and release), but does not work on the 1.5 binaries.

**Comment by lucasg** [comment]
@eodabash : `Dependencies` relies on ProcessHacker's `phlib` which need to be built using the current [Windows Driver Kit (WDK)](https://developer.microsoft.com/en-us/windows/hardware/windows-driver-kit) since it uses Windows internals features (e.g. `ntstatus.h` listing all kernel error and status codes).

**Comment by learn-more** [comment]
Is this still an issue?

**Comment by sherief** [comment]
Latest release works for me.

**Comment by ojdo** [comment]
Works here (Win10), too.

**Comment by HispidaBytes** [comment]
No problem with 1.9 and Windows 10 1809

**Comment by lucasg** [comment]
ok, closing issue
