### ISSUE TITLE
Report vcruntime140.dll as installed while actually missing.

### ISSUE THREAD

**Issue by szmcdull** [lucasg/Dependencies#51]
This is because Dependencies resolves vcruntime140.dll in its own directory. Please link with static runtime or avoid resolving Dlls in the directory of Dependencies(Gui).exe.

**Comment by lucasg** [comment]
Unfortunately, I wish I could build Dependencies with a static runtime, but it's not possible due to `/clr` compilation.

However I can set the default working directory to the binary's directory instead of Dependencies'  (you can customize it the GUI). That should solve the issue.

Thanks

**Comment by szmcdull** [comment]
If vscruntime140.dll is missing, and you change the startup directory of Dependancies(Gui).exe, will it start at all?

**Comment by lucasg** [comment]
Okay I think that's a separate issue, coming from the fact that I target Win10. I'll keep it on my to-do list, but in the meantime I'll close this issue.
