### ISSUE TITLE
clarify instructions?

### ISSUE THREAD

**Issue by Ron2** [lucasg/Dependencies#55]
Thank you for the excellent tool; it has been very useful.

I just wanted to share that I ran into some trouble following this part of the directions in the README.md file:

> download and uncompress the archive and click on it.

Since there are many executables, and since Dependencies.exe is not the right choice for most people, I think it would be clearer to say:
> download and uncompress the archive and run DependenciesGui.exe.

**Comment by lucasg** [comment]
Ok I've added your clarification to the README, and from now on tests binaries are only packaged in Debug builds, not user-facing Release builds.
