### ISSUE TITLE
WinNT5.x support

### ISSUE THREAD

**Issue by Svyatpro** [lucasg/Dependencies#68]
.NETFX 4.6.1 is required to run Dependencies. There is no NETFX 4.6.1 for XP/2003, only 4.0

**Comment by HispidaBytes** [comment]
Windows XP support in 2019 (near 2020)?
The official _extended_ support by Microsoft for this operating system ended in the 2014.. 5 years ago!

**Comment by lucasg** [comment]
I'm pretty sure I'm heading for a lot of hurt if I want to backport Dependencies to .NET 4.0 and for little value.

Dependency Walker actually support Windows XP pretty nicely, I suggest you use this tool instead.
