### ISSUE TITLE
Recent File Crash

### ISSUE THREAD

**Issue by dairymoose** [lucasg/Dependencies#74]
If you open a file with the Gui (1.9.0.0) and then on your filesystem change any folder on the path to that file, trying to open the file with the "recent" menu crashes.

e.g., 
Open file C:\Users\Jason\Downloads\testfolder2\WinSCP-5.15.2-Setup.exe
Rename folder on hard drive (testfolder2 -> testfolder3)
Using gui, go to File -> WinSCP-5.15.2-Setup.exe
Gui crashes.

**Comment by lucasg** [comment]
Ok, thanks for the issue. I've fixed it : 186ed0922eda1386b46132f19eb02be9c88a30aa .

Now the application for file presence on disk before loading it as a PE file :

![image](https://user-images.githubusercontent.com/2520861/59967107-08c5fe00-9526-11e9-8c0e-213b88f110d8.png)
