### ISSUE TITLE
Running Dependencies in a Docker container

### ISSUE THREAD

**Issue by manzanotti** [lucasg/Dependencies#77]
I have been attempting to run Dependencies on a Windows image-based Docker container, and I get the following error:

Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'ClrPhlib.dll' or one of its dependencies.  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)

I'd already added the Visual C++ redistributable to my container, which is the solution provided in https://github.com/lucasg/Dependencies/issues/24. The missing assembly is in the same folder as Dependencies.exe

Here's my Dockerfile:

```
FROM mcr.microsoft.com/dotnet/framework/runtime:4.8
ARG source

ADD https://download.visualstudio.microsoft.com/download/pr/9e04d214-5a9d-4515-9960-3d71398d98c3/1e1e62ab57bbb4bf5199e8ce88f040be/vc_redist.x64.exe /vc_redist.x64.exe
RUN powershell.exe -Command "C:/vc_redist.x64.exe" -ArgumentList '/install', '/passive', '/norestart' -NoNewWindow -Wait

ADD https://github.com/lucasg/Dependencies/releases/download/v1.9/Dependencies_x64_Debug.zip /dependencies.zip
RUN powershell.exe -NoP -NonI -Command "Expand-Archive 'C:\\dependencies.zip' 'C:\\Dependencies'" 

WORKDIR /app
COPY ${source:-obj/Docker/publish} .
ENTRYPOINT ["C:\\app\\ConsoleApp1.exe"]
```

As you can see, it's nice and simple (it's a test app that I'm using to try to work out why an asp.net app can't find a C++ DLL, ironically enough).

I'm building the Docker image on the command line:

```docker build . --no-cache -t consoleapp1:testing```

and entering it using:

```docker run -it --entrypoint="cmd.exe"```

Any idea what I've done wrong here? I've also tried it with the 4.7.2 version of the dotnet framework image.

**Comment by manzanotti** [comment]
Ok, I tried running it on my machine, and it fails with the same error. This was the x64 Debug version. I just tried it with the Release version, and that works. So is there an issue with the Debug version, or does that have some additional dependencies that the Release version doesn't?

**Comment by lucasg** [comment]
Hmm I have a deploy script that copies vcruntime dlls which is probably bugged in Debug build ...

**Comment by manzanotti** [comment]
Given that I've installed vc_redist.x64 on the container, shouldn't it work anyway? (apologies, my C++ knowledge is basically zero).

**Comment by jstallkamp** [comment]
The Redistributable only contains release versions of the relevant DLLs. Debug DLLs are not meant for distribution and are usually only available in your development environment.

**Comment by manzanotti** [comment]
Apologies, I forgot to come back and close this. You're correct, the machine I was given did not have the debug DLLs for the redist.
