### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by WWebber** [lucasg/Dependencies#78]
Nice software, but the original version uses a more readable and not blurry font and has therefore a more compact display. Why for instance is it not possible to select non blurry "MS Sans Serif" without additional line spacing?

**Comment by lucasg** [comment]
You can choose the font family in the properties windows and this setting is stored in a conf file if I remember correctly :

![image](https://user-images.githubusercontent.com/2520861/62838580-b203b780-bc7e-11e9-82db-b618d3e5ef19.png)

(Options > Properties)

**Comment by HispidaBytes** [comment]
I have not detected any problem with blurred characters. In any case, as lucasg says, from the settings it is possible to select the font.
I think the issue can be closed.

Proof of no blurriness:
![Cattura](https://user-images.githubusercontent.com/34475384/65865116-36b3ad80-e373-11e9-8166-57f1afb7d8e0.PNG)

**Comment by lucasg** [comment]
ok closing issue
