### ISSUE TITLE
Specify build steps in README

### ISSUE THREAD

**Issue by native-api** [lucasg/Dependencies#82]
I failed to figure out the way to build this project to diagnose #81.

It uses LLVM (which can be added to PATH after which the build finds `llvm-config`) but it also depends on at least https://github.com/dotnet/llilc (judging by the names of the missing headers) for which I didn't find the intended way to hook up into the project's build process.
For AppVeyor, this is somehow not a problem yet I can't see any references to llilc at https://www.appveyor.com/docs/windows-images-software/.

@lucasg , could you possibly specify the intended build procedure in the README?

**Comment by lucasg** [comment]
Ok I didn't really  explained build steps since most people are only interested in downloading the release build.

The project is pretty self contained (I detest project's dependency) the only third party dependencies are NDesk for optarg parsing and Cecil (which use lilc) for .NET domain parsing.

Ideally you should just do a : `nuget restore`  and NuGet will download all the necessary package, kinda like `npm install`

Then : `msbuild Dependencies.sln` and it should build everything

**Comment by native-api** [comment]
I tried, and it's not that simple. Building the solution fails with `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(2519,5): warning APPX0104: Certificate file 'DependenciesAppx_TemporaryKey.pfx' not found.` So I need to get a key... somewhere.

Trying to follow the steps in `appveyor.yml` -- running `Deploy-Dependencies.ps1` -- also fails.
For starters, one needs to allow running Powershell scripts -- which is prohibited by default. Then, apparently, the `$OS` envvar in AppVeyor that the scripts relies on is not what it is in a normal Windows installation.

Just try in a fresh VM, and you'll see that your environment where everything "just works" is far from the default.

**Comment by lucasg** [comment]
Yeah the `DependenciesAppx_TemporaryKey.pfx` was an attempt at creating an Appx application which failed and is not useful anymore. You just need to build the Debug and Release configuration, not the Appx.

Here below a working build "script" :

```
PS O:\Dependencies> git clone https://github.com/lucasg/Dependencies fresh
PS O:\Dependencies> cd .\fresh\
PS O:\Dependencies\fresh> C:\Users\lucas\Downloads\nuget.exe restore
MSBuild auto-detection: using msbuild version '16.1.76.45076' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin'.
Restoring NuGet package Newtonsoft.Json.11.0.2.
Restoring NuGet package Mono.Cecil.0.10.0.
Restoring NuGet package NDesk.Options.0.2.1.
Adding package 'NDesk.Options.0.2.1' to folder 'O:\Dependencies\fresh\packages'
Added package 'NDesk.Options.0.2.1' to folder 'O:\Dependencies\fresh\packages'
  GET https://api.nuget.org/v3-flatcontainer/mono.cecil/0.10.0/mono.cecil.0.10.0.nupkg
  GET https://api.nuget.org/v3-flatcontainer/newtonsoft.json/11.0.2/newtonsoft.json.11.0.2.nupkg
  OK https://api.nuget.org/v3-flatcontainer/newtonsoft.json/11.0.2/newtonsoft.json.11.0.2.nupkg 37ms
Installing Newtonsoft.Json 11.0.2.
Adding package 'Newtonsoft.Json.11.0.2' to folder 'O:\Dependencies\fresh\packages'
  OK https://api.nuget.org/v3-flatcontainer/mono.cecil/0.10.0/mono.cecil.0.10.0.nupkg 524ms
Installing Mono.Cecil 0.10.0.
Added package 'Newtonsoft.Json.11.0.2' to folder 'O:\Dependencies\fresh\packages'
Adding package 'Mono.Cecil.0.10.0' to folder 'O:\Dependencies\fresh\packages'
Added package 'Mono.Cecil.0.10.0' to folder 'O:\Dependencies\fresh\packages'

NuGet Config files used:
    C:\Users\lucas\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    C:\Users\lucas\.nuget\packages\
    https://api.nuget.org/v3/index.json
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

Installed:
    3 package(s) to packages.config projects
PS O:\Dependencies\fresh> msbuild -property:Configuration=Release Dependencies.sln
[... lots of lines ...]
Done Building Project "O:\Dependencies\fresh\test\binarycache-test\binarycache-test.csproj" (default targets).

Done Building Project "O:\Dependencies\fresh\Dependencies.sln" (default targets).


Build succeeded.
PS O:\Dependencies\fresh> .\bin\Releasex64\Dependencies.exe -h
Dependencies.exe : command line tool for dumping dependencies and various utilities.

Usage : Dependencies.exe [OPTIONS] FILE

Options :
  -h -help : display this help
  -json : activate json output.
  -apisets : dump the system's ApiSet schema (api set dll -> host dll)
  -knowndll : dump all the system's known dlls (x86 and x64)
  -manifest : dump FILE embedded manifest, if it exists.
  -sxsentries : dump all of FILE's sxs dependencies.
  -imports : dump FILE imports
  -exports : dump  FILE exports
  -modules : dump FILE resolved modules
  -chain : dump FILE whole dependency chain
```

how to get nuget : https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-nuget-cli

**Comment by native-api** [comment]
> You just need to build the Debug and Release configuration, not the Appx.

Managed it. It turns out, I needed to select "x64" or "x86" platform instead of the default "Any CPU". This is unusual and was unexpected since the program is in C#.
