### ISSUE TITLE
Virustotal detects some potential virus..

### ISSUE THREAD

**Issue by oscarbg** [lucasg/Dependencies#84]
downloaded 1.9 x64 release:
https://www.virustotal.com/gui/file/dae97fb67329b61d3d2e2a37a583a14e89bb6e3c0f7fed62e5d8a03cffb6703f/detection

**Comment by lucasg** [comment]
yep this is the same issue as https://github.com/lucasg/Dependencies/issues/26

Basically I package ProcessHacker's `peview.exe` which is incorrectly labelled as a "Hack Tool". If you want to deploy Dependencies in an environment with AVs, I recommend you to use the "peview-free" version : https://github.com/lucasg/Dependencies/releases/download/v1.9/Dependencies_x64_Release_.without_peview.exe.zip

**Comment by oscarbg** [comment]
Ok sorry for opening another issue.. closing now..
