### ISSUE TITLE
DependenciesGUI.exe crashes when dll no longer exists

### ISSUE THREAD

**Issue by netx123** [lucasg/Dependencies#93]
I have discovered that the DependenciesGUI application crashes consistently if the dll you are looking at no longer exists (if it's been moved or been renamed for example)

Steps to reproduce:
1) Launch DependenciesGUI.exe
2) Drag a dll (lets call it TEST.dll) onto the dependencies window
3) Rename the dll to TESTOLD.dll
4) In the GUI window, click the top entry in the dll dependencies treeview.
5) App Crashes

**Comment by lucasg** [comment]
Ok thanks, I've fixed it.
